name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  RUSTFLAGS: --deny warnings

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain Components
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Test (skip rune/sweep tests in CI)
        run: |
          cargo test --workspace --all-targets --all-features -- --test-threads=1 \
            --skip wallet::split::requires_rune_index \
            --skip wallet::sweep::sweep_needs_rune_index \
            --skip wallet::sweep::sweep_needs_utxos \
            --skip wallet::sweep::sweep_only_works_with_p2wpkh
