name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0

permissions:
  contents: write  # Needed for GitHub Release

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry and build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release

      - name: Package crate (for crates.io, optional)
        run: cargo package --allow-dirty

      - name: Upload crate as artifact
        uses: actions/upload-artifact@v4
        with:
          name: crate-package
          path: |
            target/package/*.crate

      - name: Upload release binary
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
