name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Build & Publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: release-cache-${{ hashFiles('**/Cargo.lock') }}

      - name: Build (Release Mode)
        run: cargo build --release

      - name: Package Crate
        run: cargo package --allow-dirty

      - name: Upload Crate
        uses: actions/upload-artifact@v4
        with:
          name: codex-crate
          path: target/package/*.crate

      - name: Upload Binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
